# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a8efc95cfdfbdbc2731797fd8055deb4c181b6ee1bdd461ec4797a1546e6949100f224e6bcbeabf4ff40f6d09d8fdbc6406b81dd915cbb55f6a5aa60a51b824

test:
  secret_key_base: 8f2fec66955d3382a7f80d207e4639fe126b21ed42547547ce07597afdb75043f47135b9b8c17c29a14fc28e9a7ba1b0e76ad470d8dcc85b62c408fac13d1094

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
